# Generated by Django 6.0.1 on 2026-01-17 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="SiteConfiguration",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "site_name",
                    models.CharField(
                        default="Capital of Fusion",
                        help_text="Nom affiché dans la navbar (ex: 'Capital of Fusion')",
                        max_length=200,
                        verbose_name="Nom du site",
                    ),
                ),
                (
                    "hero_title",
                    models.CharField(
                        default="L'EXPÉRIENCE BACHATA ULTIME",
                        help_text="Titre principal de la page d'accueil",
                        max_length=500,
                        verbose_name="Titre Hero",
                    ),
                ),
                (
                    "hero_subtitle",
                    models.TextField(
                        default="Plongez dans l'univers de la Bachata Fusion. Apprenez, progressez et connectez-vous avec la meilleure communauté de France.",
                        help_text="Description sous le titre principal",
                        verbose_name="Sous-titre Hero",
                    ),
                ),
                (
                    "hero_video_url",
                    models.URLField(
                        default="https://www.youtube.com/watch?v=XOfvM3i9S4A",
                        help_text="URL complète de la vidéo YouTube pour le fond (ex: https://www.youtube.com/watch?v=VIDEO_ID)",
                        max_length=500,
                        verbose_name="URL Vidéo YouTube",
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Configuration du Site",
                "verbose_name_plural": "Configuration du Site",
            },
        ),
    ]
