# Generated by Django 6.0 on 2026-01-31 18:38

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_siteconfiguration"),
    ]

    operations = [
        migrations.CreateModel(
            name="MenuItem",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "name",
                    models.CharField(
                        help_text="Nom affiché dans le menu",
                        max_length=100,
                        verbose_name="Nom",
                    ),
                ),
                (
                    "slug",
                    models.SlugField(
                        help_text="Identifiant unique pour l'URL", unique=True
                    ),
                ),
                (
                    "url",
                    models.CharField(
                        help_text="URL cible (ex: /cours/planning)",
                        max_length=200,
                        verbose_name="URL",
                    ),
                ),
                (
                    "icon",
                    models.CharField(
                        blank=True,
                        help_text="Nom de l'icône Lucide React (ex: GraduationCap, Calendar)",
                        max_length=50,
                        verbose_name="Icône",
                    ),
                ),
                (
                    "order",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Ordre d'affichage (plus petit = premier)",
                        verbose_name="Ordre",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Afficher cet élément dans le menu",
                        verbose_name="Actif",
                    ),
                ),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        help_text="Élément parent (vide pour les éléments racine)",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="children",
                        to="core.menuitem",
                        verbose_name="Parent",
                    ),
                ),
            ],
            options={
                "verbose_name": "Élément de menu",
                "verbose_name_plural": "Éléments de menu",
                "ordering": ["order", "name"],
            },
        ),
    ]
