# Generated by Django 6.0.1 on 2026-01-17 12:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("events", "0001_initial"),
        ("organization", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="node",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="events",
                to="organization.organizationnode",
            ),
        ),
        migrations.AddField(
            model_name="eventpass",
            name="event",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="passes",
                to="events.event",
            ),
        ),
        migrations.AddField(
            model_name="registration",
            name="event_pass",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="events.eventpass"
            ),
        ),
    ]
