# Generated by Django 6.0 on 2026-01-17 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("organization", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="organizationnode",
            name="is_visible_3d",
            field=models.BooleanField(
                default=True, help_text="Afficher cette planète dans la scène 3D"
            ),
        ),
        migrations.AddField(
            model_name="organizationnode",
            name="orbit_phase",
            field=models.FloatField(
                default=0.0, help_text="Position initiale sur l'orbite (en radians)"
            ),
        ),
        migrations.AddField(
            model_name="organizationnode",
            name="orbit_radius",
            field=models.FloatField(
                default=5.0, help_text="Distance du centre (rayon de l'orbite)"
            ),
        ),
        migrations.AddField(
            model_name="organizationnode",
            name="orbit_speed",
            field=models.FloatField(
                default=0.15, help_text="Vitesse de rotation orbitale"
            ),
        ),
        migrations.AddField(
            model_name="organizationnode",
            name="planet_color",
            field=models.CharField(
                default="#7c3aed",
                help_text="Couleur de la planète (format hex: #RRGGBB)",
                max_length=7,
            ),
        ),
        migrations.AddField(
            model_name="organizationnode",
            name="planet_scale",
            field=models.FloatField(default=0.8, help_text="Taille de la planète"),
        ),
        migrations.AddField(
            model_name="organizationnode",
            name="planet_type",
            field=models.CharField(
                choices=[
                    ("wire", "Wireframe"),
                    ("dotted", "Dotted"),
                    ("glass", "Glass"),
                    ("chrome", "Chrome"),
                    ("network", "Network"),
                    ("star", "Starburst"),
                ],
                default="glass",
                help_text="Type de visuel pour la planète 3D",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="organizationnode",
            name="rotation_speed",
            field=models.FloatField(
                default=1.0, help_text="Vitesse de rotation sur elle-même"
            ),
        ),
    ]
