# Generated by Django 6.0 on 2026-01-17 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("organization", "0003_organizationnode_is_visible_3d_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="organizationnode",
            name="model_3d",
            field=models.FileField(
                blank=True,
                help_text="Fichier .glb pour le type 'Modèle 3D'",
                null=True,
                upload_to="planets/models/",
            ),
        ),
        migrations.AddField(
            model_name="organizationnode",
            name="planet_texture",
            field=models.ImageField(
                blank=True,
                help_text="Image ou GIF pour le type 'Texture Animée'",
                null=True,
                upload_to="planets/textures/",
            ),
        ),
        migrations.AlterField(
            model_name="organizationnode",
            name="planet_type",
            field=models.CharField(
                choices=[
                    ("wire", "Wireframe"),
                    ("dotted", "Dotted"),
                    ("glass", "Glass"),
                    ("chrome", "Chrome"),
                    ("network", "Network"),
                    ("star", "Starburst"),
                    ("glb", "Modèle 3D (GLB)"),
                    ("gif", "Texture Animée (GIF)"),
                ],
                default="glass",
                help_text="Type de visuel pour la planète 3D",
                max_length=20,
            ),
        ),
    ]
