# Generated by Django 6.0 on 2026-01-17 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("organization", "0004_organizationnode_model_3d_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="organizationnode",
            name="visual_source",
            field=models.CharField(
                choices=[
                    ("preset", "Préglage (Planet Type)"),
                    ("glb", "Fichier GLB"),
                    ("gif", "Fichier GIF / Image"),
                ],
                default="preset",
                help_text="Choisissez la source du visuel : un préglage paramétrique ou un fichier",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="organizationnode",
            name="model_3d",
            field=models.FileField(
                blank=True,
                help_text="Utilisé si la source est 'Fichier GLB'",
                null=True,
                upload_to="planets/models/",
            ),
        ),
        migrations.AlterField(
            model_name="organizationnode",
            name="planet_texture",
            field=models.ImageField(
                blank=True,
                help_text="Utilisé si la source est 'Fichier GIF / Image'",
                null=True,
                upload_to="planets/textures/",
            ),
        ),
        migrations.AlterField(
            model_name="organizationnode",
            name="planet_type",
            field=models.CharField(
                choices=[
                    ("wire", "Wireframe"),
                    ("dotted", "Dotted"),
                    ("glass", "Glass"),
                    ("chrome", "Chrome"),
                    ("network", "Network"),
                    ("star", "Starburst"),
                ],
                default="glass",
                help_text="Utilisé si la source est 'Préglage'",
                max_length=20,
            ),
        ),
    ]
