# Generated by Django 6.0 on 2026-01-21 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("organization", "0005_organizationnode_visual_source_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="organizationnode",
            name="orbit_roundness",
            field=models.FloatField(
                default=0.6, help_text="Pour Squircle : 0 = carré, 1 = cercle"
            ),
        ),
        migrations.AddField(
            model_name="organizationnode",
            name="orbit_shape",
            field=models.CharField(
                choices=[
                    ("circle", "Circulaire"),
                    ("squircle", "Squircle (Carré arrondi)"),
                ],
                default="circle",
                help_text="Forme de l'orbite",
                max_length=10,
            ),
        ),
    ]
