# Generated by Django 6.0 on 2026-01-31 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("organization", "0006_organizationnode_orbit_roundness_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="organizationnode",
            name="entry_speed",
            field=models.FloatField(
                default=0.4, help_text="Vitesse de la trajectoire d'entrée"
            ),
        ),
        migrations.AddField(
            model_name="organizationnode",
            name="entry_start_x",
            field=models.FloatField(
                default=-60.0, help_text="Position de départ X (ligne d'entrée)"
            ),
        ),
        migrations.AddField(
            model_name="organizationnode",
            name="entry_start_y",
            field=models.FloatField(
                default=0.0, help_text="Position de départ Y (ligne d'entrée)"
            ),
        ),
        migrations.AddField(
            model_name="organizationnode",
            name="entry_start_z",
            field=models.FloatField(
                blank=True,
                help_text="Position de départ Z (si null, utilise orbit_radius)",
                null=True,
            ),
        ),
    ]
