# Generated by Django 6.0 on 2026-01-31 19:04

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("organization", "0007_add_entry_animation_fields"),
    ]

    operations = [
        migrations.AddField(
            model_name="organizationnode",
            name="content",
            field=models.TextField(
                blank=True,
                help_text="Contenu riche affiché dans l'overlay (supporte le markdown)",
                verbose_name="Contenu détaillé",
            ),
        ),
        migrations.AddField(
            model_name="organizationnode",
            name="cover_image",
            field=models.ImageField(
                blank=True,
                help_text="Image principale affichée dans l'overlay (format 16:9 recommandé)",
                null=True,
                upload_to="nodes/covers/",
                verbose_name="Image de couverture",
            ),
        ),
        migrations.AddField(
            model_name="organizationnode",
            name="cta_text",
            field=models.CharField(
                blank=True,
                default="En savoir plus",
                help_text="Texte du bouton d'action principal",
                max_length=50,
                verbose_name="Texte du bouton CTA",
            ),
        ),
        migrations.AddField(
            model_name="organizationnode",
            name="cta_url",
            field=models.CharField(
                blank=True,
                help_text="Lien vers la page de destination (ex: /cours)",
                max_length=200,
                verbose_name="URL du bouton CTA",
            ),
        ),
        migrations.AddField(
            model_name="organizationnode",
            name="short_description",
            field=models.CharField(
                blank=True,
                help_text="Description courte affichée sous le titre (max 300 caractères)",
                max_length=300,
                verbose_name="Accroche courte",
            ),
        ),
        migrations.CreateModel(
            name="NodeEvent",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("title", models.CharField(max_length=200, verbose_name="Titre")),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="Description"),
                ),
                (
                    "start_datetime",
                    models.DateTimeField(verbose_name="Date et heure de début"),
                ),
                (
                    "end_datetime",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Date et heure de fin"
                    ),
                ),
                (
                    "location",
                    models.CharField(blank=True, max_length=200, verbose_name="Lieu"),
                ),
                (
                    "image",
                    models.ImageField(
                        blank=True, null=True, upload_to="events/", verbose_name="Image"
                    ),
                ),
                (
                    "is_featured",
                    models.BooleanField(
                        default=False,
                        help_text="Afficher cet événement en priorité",
                        verbose_name="Mis en avant",
                    ),
                ),
                (
                    "external_url",
                    models.URLField(
                        blank=True,
                        help_text="Lien vers une page externe (billetterie, inscription, etc.)",
                        verbose_name="Lien externe",
                    ),
                ),
                (
                    "node",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="node_events",
                        to="organization.organizationnode",
                        verbose_name="Noeud",
                    ),
                ),
            ],
            options={
                "verbose_name": "Événement",
                "verbose_name_plural": "Événements",
                "ordering": ["start_datetime"],
            },
        ),
    ]
